Controllers/FemininoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Projeto1.Data;
using Projeto1.Models;

namespace Projeto1.Controllers
{
    public class FemininoController : Controller
    {
        private readonly Context _context;

        public FemininoController(Context context)
        {
            _context = context;
        }
       
        // GET: Feminino
        public async Task<IActionResult> IndexFeminino()
        {
              return _context.Feminino != null ? 
                          View(await _context.Feminino.ToListAsync()) :
                          Problem("Entity set 'FemininoProjeto1Context.ElencoFeminino'  is null.");
        }

        // GET: Feminino/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Feminino == null)
            {
                return NotFound();
            }

            var elencoFeminino = await _context.Feminino
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (elencoFeminino == null)
            {
                return NotFound();
            }

            return View(elencoFeminino);
        }

        // GET: Feminino/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Matricula,Nome,Posicao")] ElencoFeminino elencoFeminino)
        {
            if (ModelState.IsValid)
            {
                _context.Add(elencoFeminino);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexFeminino));
            }
            return View(elencoFeminino);
        }

        // GET: Feminino/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Feminino == null)
            {
                return NotFound();
            }

            var elencoFeminino = await _context.Feminino.FindAsync(id);
            if (elencoFeminino == null)
            {
                return NotFound();
            }
            return View(elencoFeminino);
        }

        // POST: Feminino/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Matricula,Nome,Posicao")] ElencoFeminino elencoFeminino)
        {
            if (id != elencoFeminino.Matricula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(elencoFeminino);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ElencoFemininoExists(elencoFeminino.Matricula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(IndexFeminino));
            }
            return View(elencoFeminino);
        }

        // GET: Feminino/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Feminino == null)
            {
                return NotFound();
            }

            var elencoFeminino = await _context.Feminino
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (elencoFeminino == null)
            {
                return NotFound();
            }

            return View(elencoFeminino);
        }

        // POST: Feminino/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Feminino == null)
            {
                return Problem("Entity set 'FemininoProjeto1Context.ElencoFeminino'  is null.");
            }
            var elencoFeminino = await _context.Feminino.FindAsync(id);
            if (elencoFeminino != null)
            {
                _context.Feminino.Remove(elencoFeminino);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexFeminino));
        }

        private bool ElencoFemininoExists(int id)
        {
          return (_context.Feminino?.Any(e => e.Matricula == id)).GetValueOrDefault();
        }
        
    }
}

Controllers/MasculinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projeto1.Data;
using Projeto1.Models;

namespace Projeto1.Controllers
{
    public class MasculinoController : Controller
    {
        private readonly Context _context;

        public MasculinoController(Context context)
        {
            _context = context;
        }

        // GET: Masculino
        public async Task<IActionResult> Index()
        {
              return _context.Jogadores != null ? 
                          View(await _context.Jogadores.ToListAsync()) :
                          Problem("Entity set 'Context.Jogadores'  is null.");
        }

        // GET: Masculino/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jogadores == null)
            {
                return NotFound();
            }

            var elencoMasculino = await _context.Jogadores
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (elencoMasculino == null)
            {
                return NotFound();
            }

            return View(elencoMasculino);
        }

        // GET: Masculino/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Matricula,Nome,Posicao")] ElencoMasculino elencoMasculino)
        {
            if (ModelState.IsValid)
            {
                _context.Add(elencoMasculino);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(elencoMasculino);
        }

        // GET: Masculino/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jogadores == null)
            {
                return NotFound();
            }

            var elencoMasculino = await _context.Jogadores.FindAsync(id);
            if (elencoMasculino == null)
            {
                return NotFound();
            }
            return View(elencoMasculino);
        }

        // POST: Masculino/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Matricula,Nome,Posicao")] ElencoMasculino elencoMasculino)
        {
            if (id != elencoMasculino.Matricula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(elencoMasculino);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ElencoMasculinoExists(elencoMasculino.Matricula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(elencoMasculino);
        }

        // GET: Masculino/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jogadores == null)
            {
                return NotFound();
            }

            var elencoMasculino = await _context.Jogadores
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (elencoMasculino == null)
            {
                return NotFound();
            }

            return View(elencoMasculino);
        }

        // POST: Masculino/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jogadores == null)
            {
                return Problem("Entity set 'Context.Jogadores'  is null.");
            }
            var elencoMasculino = await _context.Jogadores.FindAsync(id);
            if (elencoMasculino != null)
            {
                _context.Jogadores.Remove(elencoMasculino);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ElencoMasculinoExists(int id)
        {
          return (_context.Jogadores?.Any(e => e.Matricula == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projeto1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h2>TREVO F.C</h2></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Projetos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Nossa Historia</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Masculino" asp-action="Index">Elenco Masculino</a>
                        </li>  

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Feminino" asp-action="IndexFeminino">Elenco Feminino</a>
                        </li>      
                                               
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Projeto1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>